# test action creation following https://www.philschmid.de/create-custom-github-action-in-4-steps
name: 'Interact with Lifebit CloudOS with cloudos-cli'
branding:
  icon: 'cloud'
  color: 'blue'
description: 'Interact with Lifebit CloudOS programmatically using the lifebit-ai/cloudos-cli'
inputs:
  apikey:
    description: 'Lifebit CloudOS user personal API token'
    required: true
  cloudos_url:
    description: 'The Lifebit CloudOS application hostname without a trailing backslash eg https://cloudos.lifebit.ai'
    required: true
  workspace_id:
    description: 'The Lifebit CloudOS workspace id. It Can be found under Settings in the web application.'
    required: true
  project_name:
    description: 'The Lifebit CloudOS workspace id. It can be created and selected from the Lifebit CloudOS web application user interface under Projects.'
    required: true
  workflow_name:
    description: 'The Lifebit CloudOS workflow name. It can be created and selected from the Lifebit CloudOS web application user interface under Pipelines & Tools.'
    required: true
  job_config:
    description: 'A local file with suffix .config, that includes only a params scope enclosed in curly brackets. The file should contain parameter key:value pairs. For example see: https://github.com/lifebit-ai/cloudos-cli/blob/dev/cloudos/examples/rnatoy.config'
    required: false
  nextflow_profile:
    description: 'One or many comma separated strings, indicating the nextflow profile/s to use with your job. Only applicable to Nextflow workflows.'
    required: false
  git_commit:
    description: 'The exact whole 40 character commit hash to run for the selected pipeline. If not specified it defaults to the last commit of the default branch.'
    required: false
  git_tag:
    description: 'The version tag of the chosen workflow repository. It must exist in the repository'
    required: false
  job_name:
    description: 'A name to assign to the job run.'
    required: true
    default: job-via-github-actions-ci
  instance_type:
    description: 'The type of AWS EC2 instance to use as master node for the job eg c5.xlarge'
    required: false
  instance_disk:
    description: 'Disk storage in GB to be used for the master node vm.'
    required: false
  storage_mode:
    description: 'The storage mode to use. Available options: [regular,lustre]. Regular is EBS.'
    required: false
  lustre_size:
    description: 'The lustre storage to be used when --storage-mode=lustre, in GB. It should be 1200 or a multiple of it.'
    required: false
  wait_time:
    description: 'Max time to wait (in seconds) to job completion'
    required: false
  wdl_mainfile:
    description: 'For WDL workflows, which mainFile (.wdl) is configured to use (string). This is defined when the WDL repository is imported under Pipelines & Tools using the Lifebit CloudOS web application user interface.'
    required: false
  wdl_importsfile:
    description: 'For WDL workflows, which importsFile (.zip) is configured to use (string). This is defined when the WDL repository is imported under Pipelines & Tools using the Lifebit CloudOS web application user interface.'
    required: false
  cromwell_token:
    description: 'Specific Cromwell server authentication token. Only required for WDL jobs'
    required: false
  repository_platform:
    description: 'Name of the repository platform of the workflow. Default=github.'
    required: false
  request_interval: 
    description: 'Request interval in seconds. The options is influencing the request interval for receiving the job status when --wait-completion is used'
    required: false
  cost_limit:
    description: 'Cost limit in USD. If the job exceeds the defined cost limit, the job will be aborted. It is advised to always use a cost limit.'
    required: false
  cloudos_cli_flags:
    description: 'Additional cloudos-cli flags, space separated eg "--spot --resumable". Available options: [--spot, --batch, --resumable, --verbose, --wait-completion]'
    required: false
    default: ''
  dry_run:
    description: 'Mode of execution for the action, by default the API call will be sent. Set to dry_run: true if you only want to print the command (strips secrets before printing).'
    required: false
    default: false
outputs:
   job_id:
     description: 'Job ID from Lifebit CloudOS cloudos-cli'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apikey }}
    - ${{ inputs.cloudos_url }}
    - ${{ inputs.workspace_id }}
    - ${{ inputs.project_name }}
    - ${{ inputs.workflow_name }}
    - ${{ inputs.job_config }}
    - ${{ inputs.nextflow_profile }}
    - ${{ inputs.git_commit }}
    - ${{ inputs.git_tag }}
    - ${{ inputs.job_name }}
    - ${{ inputs.instance_type }}
    - ${{ inputs.instance_disk }}
    - ${{ inputs.storage_mode }}
    - ${{ inputs.lustre_size }}
    - ${{ inputs.wait_time }}
    - ${{ inputs.wdl_mainfile }}
    - ${{ inputs.wdl_importsfile }}
    - ${{ inputs.cromwell_token }}
    - ${{ inputs.repository_platform }}
    - ${{ inputs.request_interval}}
    - ${{ inputs.cloudos_cli_flags}}
    - ${{ inputs.dry_run}}
